name: cicd

on: push

#on:
#  schedule:
#    -cron: "0 21 * *"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Download dependencies
        run: npm install

      - name: Run tests
        run: npm run test
